name:                hath
version:             0.1.0.0
github:              "libscott/hath"
license:             BSD3
author:              "Scott Sadler"
maintainer:          "example@example.com"
copyright:           "2018 Scott Sadler"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/hath#readme>

dependencies:
- base >= 4.7 && < 5
- aeson
- aeson-pretty
- aeson-quick
- ansi-wl-pprint
- attoparsec
- base16-bytestring
- bytestring
- cereal
- conduit
- conduit-extra
- containers
- cryptonite
- directory
- entropy
- haskoin-core
- hassembly-evm
- http-conduit
- network
- memory
- microlens
- microlens-platform
- monad-logger
- mtl
- ndjson-conduit
- optparse-applicative
- pretty-simple
- QuickCheck
- secp256k1
- text
- transformers
- unordered-containers

library:
  source-dirs: src

executables:
  hath:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hath

tests:
  hath-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hath
    - tasty
    - tasty-hunit
    - tasty-golden
    - tasty-quickcheck
    - quickcheck-instances

